// services/demoData.js (or services/demo.js)

export const DEMO_EVALUATION_RESULTS = {
  dataset_name: "NOAA GHCN-Daily Weather Panel",
  spec_name: "noaa_winner.yaml",
  self_check_max: 0.0,
  mean_distance: 0.2314,
  family_scores: {
    distributional: 0.0984,
    trend: 0.4128,
    seasonality: 0.1652,
    local: 0.2491,
  },
  setting_scores: {
    A: 0.2105,
    B: 0.1843,
    C: 0.2994,
  },
  instances: [
    // --------------------------------------------------------------------------
    // 1. DISTRIBUTIONAL FAMILY
    // --------------------------------------------------------------------------
    {
      instance_id: "latzone_temp_monthly::A::mean::LATITUDE[0,35)/TMAX",
      view: "latzone_temp_monthly",
      setting: "A",
      family: "distributional",
      qid: "mean",
      focus: "LATITUDE[0,35)/TMAX",
      kind: "scalar",
      real_value: 211.06,
      synth_value: 204.12,
      distance: 0.0167,
      real_summary: 211.06,
      synth_summary: 204.12,
    },
    {
      instance_id: "latzone_temp_monthly::A::variance::LATITUDE[0,35)/TMAX",
      view: "latzone_temp_monthly",
      setting: "A",
      family: "distributional",
      qid: "variance",
      focus: "LATITUDE[0,35)/TMAX",
      kind: "scalar",
      real_value: 1245.8,
      synth_value: 1102.3,
      distance: 0.0611,
      real_summary: 1245.8,
      synth_summary: 1102.3,
    },
    {
      instance_id: "latzone_temp_monthly::B::corr_matrix::LATITUDE[0,35)",
      view: "latzone_temp_monthly",
      setting: "B",
      family: "distributional",
      qid: "corr_matrix",
      focus: "LATITUDE[0,35)",
      kind: "matrix",
      real_value: [
        [1.0, 0.42, 0.38],
        [0.42, 1.0, 0.89],
        [0.38, 0.89, 1.0],
      ],
      synth_value: [
        [1.0, 0.39, 0.31],
        [0.39, 1.0, 0.82],
        [0.31, 0.82, 1.0],
      ],
      distance: 0.0824,
      real_summary: { shape: [3, 3], mean: 0.675 },
      synth_summary: { shape: [3, 3], mean: 0.638 },
    },
    {
      instance_id: "latzone_temp_monthly::C::series_mean_distribution::TMAX",
      view: "latzone_temp_monthly",
      setting: "C",
      family: "distributional",
      qid: "series_mean_distribution",
      focus: "TMAX",
      kind: "distribution",
      real_value: [211.06, 178.42, 142.15, 95.84, 12.33],
      synth_value: [204.12, 169.88, 138.5, 88.12, 10.95],
      distance: 0.1245,
      real_summary: { shape: [5], mean: 127.96 },
      synth_summary: { shape: [5], mean: 122.31 },
    },

    // --------------------------------------------------------------------------
    // 2. TREND & DRIFT FAMILY
    // --------------------------------------------------------------------------
    {
      instance_id: "latzone_trend_monthly::A::linear_trend::LATITUDE[0,35)/TMAX",
      view: "latzone_trend_monthly",
      setting: "A",
      family: "trend",
      qid: "linear_trend",
      focus: "LATITUDE[0,35)/TMAX",
      kind: "scalar",
      real_value: 0.034,
      synth_value: -0.012,
      distance: 0.6667,
      real_summary: 0.034,
      synth_summary: -0.012,
    },
    {
      instance_id: "latzone_temp_monthly::A::acf_lag1::LATITUDE[0,35)/TMAX",
      view: "latzone_temp_monthly",
      setting: "A",
      family: "trend",
      qid: "acf_lag1",
      focus: "LATITUDE[0,35)/TMAX",
      kind: "correlation",
      real_value: 0.824,
      synth_value: 0.761,
      distance: 0.0315,
      real_summary: 0.824,
      synth_summary: 0.761,
    },
    {
      instance_id: "latzone_temp_monthly::B::corr_structure_variation::LATITUDE[0,35)",
      view: "latzone_temp_monthly",
      setting: "B",
      family: "trend",
      qid: "corr_structure_variation",
      focus: "LATITUDE[0,35)",
      kind: "scalar",
      real_value: 0.045,
      synth_value: 0.082,
      distance: 0.2913,
      real_summary: 0.045,
      synth_summary: 0.082,
    },
    {
      instance_id: "latzone_temp_monthly::C::system_avg_trajectory::TMAX",
      view: "latzone_temp_monthly",
      setting: "C",
      family: "trend",
      qid: "system_avg_trajectory",
      focus: "TMAX",
      kind: "vector",
      real_value: [85.2, 92.4, 125.6, 170.1, 215.4, 248.9, 262.1, 255.3, 221.7, 168.4, 118.2, 89.5],
      synth_value: [80.1, 88.7, 120.3, 162.8, 208.5, 239.4, 251.2, 246.0, 212.8, 159.1, 111.4, 83.9],
      distance: 0.0482,
      real_summary: { shape: [12], mean: 171.07 },
      synth_summary: { shape: [12], mean: 163.67 },
    },

    // --------------------------------------------------------------------------
    // 3. SEASONALITY & RECURRENCE FAMILY
    // --------------------------------------------------------------------------
    {
      instance_id: "latzone_temp_monthly::A::spectral_concentration::LATITUDE[0,35)/TMAX",
      view: "latzone_temp_monthly",
      setting: "A",
      family: "seasonality",
      qid: "spectral_concentration",
      focus: "LATITUDE[0,35)/TMAX",
      kind: "unit",
      real_value: 0.9789,
      synth_value: 0.8942,
      distance: 0.0847,
      real_summary: 0.9789,
      synth_summary: 0.8942,
    },
    {
      instance_id: "latzone_temp_monthly::A::seasonal_strength_stl::LATITUDE[0,35)/TMAX",
      view: "latzone_temp_monthly",
      setting: "A",
      family: "seasonality",
      qid: "seasonal_strength_stl",
      focus: "LATITUDE[0,35)/TMAX",
      kind: "unit",
      real_value: 0.9912,
      synth_value: 0.9451,
      distance: 0.0461,
      real_summary: 0.9912,
      synth_summary: 0.9451,
    },
    {
      instance_id: "latzone_temp_monthly::A::acf_profile::LATITUDE[0,35)/TMAX",
      view: "latzone_temp_monthly",
      setting: "A",
      family: "seasonality",
      qid: "acf_profile",
      focus: "LATITUDE[0,35)/TMAX",
      kind: "vector",
      real_value: [1.0, 0.82, 0.41, -0.15, -0.62, -0.88, -0.92, -0.71, -0.22, 0.35, 0.78, 0.95],
      synth_value: [1.0, 0.75, 0.32, -0.21, -0.55, -0.8, -0.85, -0.62, -0.15, 0.28, 0.69, 0.88],
      distance: 0.0845,
      real_summary: { shape: [12], mean: 0.035 },
      synth_summary: { shape: [12], mean: 0.019 },
    },
    {
      instance_id: "latzone_temp_monthly::C::shared_dominant_freq_count::TMAX",
      view: "latzone_temp_monthly",
      setting: "C",
      family: "seasonality",
      qid: "shared_dominant_freq_count",
      focus: "TMAX",
      kind: "count",
      real_value: 10,
      synth_value: 8,
      distance: 0.1111,
      real_summary: 10,
      synth_summary: 8,
    },

    // --------------------------------------------------------------------------
    // 4. LOCAL PATTERNS FAMILY (Matrix Profiles)
    // --------------------------------------------------------------------------
    {
      instance_id: "latzone_temp_monthly::A::topk_motifs|shape::LATITUDE[0,35)/TMAX",
      view: "latzone_temp_monthly",
      setting: "A",
      family: "local",
      qid: "topk_motifs|shape",
      focus: "LATITUDE[0,35)/TMAX",
      kind: "vector",
      mode: "shape",
      real_value: [-1.45, -1.22, -0.98],
      synth_value: [-0.85, -0.42, -0.12],
      distance: 0.352,
      real_summary: { shape: [3], mean: -1.217 },
      synth_summary: { shape: [3], mean: -0.463 },
    },
    {
      instance_id: "latzone_temp_monthly::A::topk_discords|amp::LATITUDE[0,35)/TMAX",
      view: "latzone_temp_monthly",
      setting: "A",
      family: "local",
      qid: "topk_discords|amp",
      focus: "LATITUDE[0,35)/TMAX",
      kind: "vector",
      mode: "amp",
      real_value: [2.83, 2.66, 2.62],
      synth_value: [2.15, 1.98, 1.84],
      distance: 0.1458,
      real_summary: { shape: [3], mean: 2.703 },
      synth_summary: { shape: [3], mean: 1.99 },
    },
    {
      instance_id: "latzone_temp_monthly::A::turning_point_rate::LATITUDE[0,35)/TMAX",
      view: "latzone_temp_monthly",
      setting: "A",
      family: "local",
      qid: "turning_point_rate",
      focus: "LATITUDE[0,35)/TMAX",
      kind: "unit",
      mode: "",
      real_value: 0.185,
      synth_value: 0.242,
      distance: 0.057,
      real_summary: 0.185,
      synth_summary: 0.242,
    },
  ],
};